name: Build and upload Frigate python package to PyPI and Conda

on:
  push:
    branches:
      - "branch-*"
    tags:
      - "v**"
      - "!v**a"

jobs:
  build_and_upload:
    name: Build Frigate Package
    uses: ./.github/workflows/build_conda_and_pypi.yaml
    with:
      upload: true
