on:
  workflow_call:
    upload:
      build_type:
        required: true
        type: boolean

jobs:
  build-and-upload-pypi:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3
        with:
          ref: ${{ github.event.pull_request.head.sha }}
          fetch-depth: 0

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.10"

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install wheel setuptools twine

      - name: Build package
        run: python setup.py sdist bdist_wheel

      - name: Upload to PyPI
        if: ${{ inputs.upload == 'true' }}
        env:
          TWINE_USERNAME: rapidsai
          TWINE_PASSWORD: ${{ secrets.PYPI_API_TOKEN }}
        run: twine upload --skip-existing dist/*
