name: Build and upload Frigate python package to PyPI and Conda

on:
  push:
    branches:
      - "branch-*"
    tags:
      - v[0-9][0-9].[0-9][0-9].[0-9][0-9]

jobs:
  build_and_upload_pypi:
    name: Build Frigate Package
    uses: ./.github/workflows/build_pypi.yaml
    with:
      upload: true

  build_and_upload_conda:
    name: Build Frigate Package
    uses: ./.github/workflows/build_conda.yaml
    with:
      upload: true
